image: python:latest
pages:
  stage: deploy
  only:
    - main
  script:
    - rm -rf public
    - pip install mkdocs-material
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
